### PR TITLE
fix(replication): add proper handling for pool restarts during replication

### LINKED ISSUE #914: [Resharding] pool is shut down
**PgDog version**
`v0.1.36` `veb5ab65`

**Description**
We have finally completed the [data sync](https://github.com/pgdogdev/pgdog/issues/894) stage for a large database, and we received an error when completing the COPY execution:

```
2026-04-18T02:31:14.592188Z ERROR [task: 1] pool: pool is shut down
```

The error in the log is not informative, it is not clear what exactly the problem is.

logical replication then did not start, the slot is not active:

```
db_name=# select now(), active, slot_name, pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), confirmed_flush_lsn)) as lag
from pg_replication_slots
where slot_type = 'logical';
              now              | active |             slot_name              |   lag   
-------------------------------+--------+------------------------------------+---------
 2026-04-18 10:25:02.026172+00 | f      | __pgdog_repl_200ydsmxvvvbtco6kfu_0 | 2855 GB
(1 row)
```

Perhaps this is due to the absence of PK in the two sharded tables. We used REPLICA IDENTITY FULL as a workaround, but judging by this [article](https://pgdog.dev/blog/shard-postgres-with-one-command), this is not enough due to the rewriting of the query in upsert.

**Based on this, I have a few questions:**

1. Why didn’t PgDog perform pre-checks on the source before starting the data copy?
    - If a primary key is a strict requirement, it seems the process should not start without it.
2. Would it be sufficient to create the primary key on the shards after copying the schema, but before starting data replication?
    - Adding a primary key on a high-load source with tens of terabytes of data is quite challenging.
3. Is a primary key strictly required, or would a unique index be sufficient?

**Logs**

```
...
2026-04-18T02:30:44.103640Z  INFO synced 180164.520 MB for table "public"."table_name" position 8E06A/B8684DD0 [40.066 MB/sec]
2026-04-18T02:30:49.104770Z  INFO synced 180385.689 MB for table "public"."table_name" position 8E06A/B8684DD0 [44.234 MB/sec]
2026-04-18T02:30:53.089845Z DEBUG running healthcheck ";" [app_user@10.*.**.***:5441/db_name]
2026-04-18T02:30:53.089854Z DEBUG running healthcheck ";" [postgres@10.*.**.***:5434/db_name]
2026-04-18T02:30:53.089840Z DEBUG running healthcheck ";" [app_user@10.*.**.***:5442/db_name]
2026-04-18T02:30:53.089870Z DEBUG running healthcheck ";" [postgres@10.*.**.***:5440/db_name]
2026-04-18T02:30:53.089885Z DEBUG running healthcheck ";" [postgres@10.*.**.***:5441/db_name]
2026-04-18T02:30:53.089902Z DEBUG running healthcheck ";" [app_user@10.*.**.***:5440/db_name]
2026-04-18T02:30:53.089924Z DEBUG running healthcheck ";" [app_user@10.*.**.***:5434/db_name]
2026-04-18T02:30:53.089840Z DEBUG running healthcheck ";" [postgres@10.*.**.***:5442/db_name]
2026-04-18T02:30:53.090000Z DEBUG [cleanup] no cleanup needed, server in "idle" state [postgres@10.*.**.***:5441/db_name]
2026-04-18T02:30:53.090044Z DEBUG [cleanup] no cleanup needed, server in "idle" state [postgres@10.*.**.***:5442/db_name]
2026-04-18T02:30:53.090066Z DEBUG [cleanup] no cleanup needed, server in "idle" state [postgres@10.*.**.***:5434/db_name]
2026-04-18T02:30:53.090094Z DEBUG [cleanup] no cleanup needed, server in "idle" state [app_user@10.*.**.***:5440/db_name]
2026-04-18T02:30:53.090122Z DEBUG [cleanup] no cleanup needed, server in "idle" state [app_user@10.*.**.***:5442/db_name]
2026-04-18T02:30:53.090154Z DEBUG [cleanup] no cleanup needed, server in "idle" state [app_user@10.*.**.***:5434/db_name]
2026-04-18T02:30:53.091155Z DEBUG [cleanup] no cleanup needed, server in "idle" state [app_user@10.*.**.***:5441/db_name]
2026-04-18T02:30:53.125369Z DEBUG [cleanup] no cleanup needed, server in "idle" state [postgres@10.*.**.***:5440/db_name]
2026-04-18T02:30:54.105642Z  INFO synced 180726.993 MB for table "public"."table_name" position 8E06A/B8684DD0 [68.261 MB/sec]
2026-04-18T02:30:59.106681Z  INFO synced 181131.943 MB for table "public"."table_name" position 8E06A/B8684DD0 [80.990 MB/sec]
2026-04-18T02:31:04.107634Z  INFO synced 181511.931 MB for table "public"."table_name" position 8E06A/B8684DD0 [75.998 MB/sec]
2026-04-18T02:31:09.108759Z  INFO synced 181905.449 MB for table "public"."table_name" position 8E06A/B8684DD0 [78.704 MB/sec]
2026-04-18T02:31:14.110437Z  INFO synced 182238.426 MB for table "public"."table_name" position 8E06A/B8684DD0 [66.595 MB/sec]
2026-04-18T02:31:14.553397Z  INFO closing server connection [postgres@10.*.**.***:5440/db_name, state: idle, reason: other]
2026-04-18T02:31:14.553549Z  INFO closing server connection [postgres@10.*.**.***:5441/db_name, state: idle, reason: other]
2026-04-18T02:31:14.553579Z  INFO closing server connection [postgres@10.*.**.***:5442/db_name, state: idle, reason: other]
2026-04-18T02:31:14.554684Z DEBUG streaming replication on [postgres@10.*.**.***:5434/db_name]
2026-04-18T02:31:14.554691Z DEBUG replication from slot "__pgdog_l7bmggqbvfgdyaoc192yzx3q" started [postgres@10.*.**.***:5434/db_name]
2026-04-18T02:31:14.554696Z DEBUG confirmed 2498548778683856 flushed [postgres@10.*.**.***:5434/db_name]
2026-04-18T02:31:14.558873Z DEBUG slot "__pgdog_l7bmggqbvfgdyaoc192yzx3q" drained [postgres@10.*.**.***:5434/db_name]
2026-04-18T02:31:14.558888Z  INFO data sync for "public"."table_name" finished at lsn 8E06A/B8684DD0 [postgres@10.*.**.***:5434/db_name]
2026-04-18T02:31:14.558898Z  INFO closing server connection [postgres@10.*.**.***:5434/db_name, state: idle, reason: other]
2026-04-18T02:31:14.564756Z  INFO table sync for 276 tables complete [db_name, shard: 0]
2026-04-18T02:31:14.592129Z  INFO closing server connection [postgres@10.*.**.***:5434/db_name, state: idle, reason: other]
2026-04-18T02:31:14.592188Z ERROR [task: 1] pool: pool is shut down
2026-04-18T02:31:23.090132Z DEBUG running healthcheck ";" [postgres@10.*.**.***:5440/db_name]
2026-04-18T02:31:23.090136Z DEBUG running healthcheck ";" [app_user@10.*.**.***:5440/db_name]
2026-04-18T02:31:23.090234Z DEBUG running healthcheck ";" [postgres@10.*.**.***:5441/db_name]
2026-04-18T02:31:23.090142Z DEBUG running healthcheck ";" [postgres@10.*.**.***:5442/db_name]
2026-04-18T02:31:23.090161Z DEBUG running healthcheck ";" [app_user@10.*.**.***:5434/db_name]
2026-04-18T02:31:23.090178Z DEBUG running healthcheck ";" [app_user@10.*.**.***:5441/db_name]
2026-04-18T02:31:23.090190Z DEBUG running healthcheck ";" [postgres@10.*.**.***:5434/db_name]
2026-04-18T02:31:23.090466Z DEBUG [cleanup] no cleanup needed, server in "idle" state [postgres@10.*.**.***:5441/db_name]
2026-04-18T02:31:23.090471Z DEBUG [cleanup] no cleanup needed, server in "idle" state [postgres@10.*.**.***:5442/db_name]
2026-04-18T02:31:23.090478Z DEBUG [cleanup] no cleanup needed, server in "idle" state [postgres@10.*.**.***:5440/db_name]
2026-04-18T02:31:23.090484Z DEBUG [cleanup] no cleanup needed, server in "idle" state [app_user@10.*.**.***:5440/db_name]
2026-04-18T02:31:23.090219Z DEBUG running healthcheck ";" [app_user@10.*.**.***:5442/db_name]
...
```

**Configuration**
`pgdog.toml`

```
[general]
workers = 20

[[databases]]
name = "db_name"
host = "10.*.**.***"
port = 5434
role = "primary"
database_name = "db_name"

[[databases]]
name = "db_name_sharded"
database_name = "db_name"
host = "10.*.**.***"
port = 5440
role = "primary"
shard = 0

[[databases]]
name = "db_name_sharded"
database_name = "db_name"
host = "10.*.**.***"
port = 5441
role = "primary"
shard = 1

[[databases]]
name = "db_name_sharded"
database_name = "db_name"
host = "10.*.**.***"
port = 5442
role = "primary"
shard = 2

[[sharded_tables]]
database = "db_name_sharded"
column = "s_id"
data_type = "bigint"

[[sharded_tables]]
database = "db_name_sharded"
name = "table3"
column = "ss"
data_type = "varchar"

[[sharded_tables]]
database = "db_name_sharded"
name = "table4"
column = "ss"
data_type = "varchar"

[admin]
password = "******"
```

`users.toml`
```
[[users]]
name = "postgres"
password = "********"
database = "db_name"
schema_admin = true

[[users]]
name = "postgres"
password = "********"
database = "db_name_sharded"
schema_admin = true

[[users]]
name = "app_user"
password = "********"
database = "db_name"

[[users]]
name = "app_user"
password = "********"
database = "db_name_sharded"
```

### PR DESCRIPTION
**Pull request by meskill**

### CODE REVIEW

File: pgdog/src/backend/pool/pool_impl.rs [hunk 1]
```diff
@@ -358,8 +358,15 @@ impl Pool {
 
     /// Shutdown the pool.
     pub fn shutdown(&self) {
+        let addr = self.addr();
+        warn!(
+            host = %addr.host,
+            port = addr.port,
+            database = %addr.database_name,
+            user = %addr.user,
+            "pool offline: connection pool shut down"
```
Comment (levkk) [inline pgdog/src/backend/pool/pool_impl.rs:367]: You don't want to log that. This "shutdown" isn't actually shutdown, it just destroys this object. We replace it with a brand new one atomically. This could make people think we are shutting down causing panic :D

File: pgdog/src/backend/replication/logical/publisher/publisher_impl.rs [hunk 2]
```diff
@@ -314,6 +323,15 @@ impl Publisher {
         // Fetch schema.
         self.sync_tables(true, dest).await?;
 
+        // Validate all tables support replication before committing to
+        // what can be a multi-hour copy.  A table with no primary key or
+        // unique replica-identity index cannot be replicated correctly.
+        for tables in self.tables.values() {
```
Comment (levkk) [inline pgdog/src/backend/replication/logical/publisher/publisher_impl.rs:329]: This is great, we should of done it long time ago.

File: pgdog/src/backend/replication/logical/publisher/table.rs [hunk 3]
```diff
@@ -72,11 +72,14 @@ impl Table {
     }
 
     /// Check that the table supports replication.
+    ///
+    /// Requires at least one column with a replica identity flag. Tables with
+    /// REPLICA IDENTITY FULL or NOTHING have no identity columns and fail here
```
Comment (levkk) [inline pgdog/src/backend/replication/logical/publisher/table.rs:77]: I would double check that. If this is true, we need to have a special query to detect `REPLICA IDENTITY FULL` and use that as the key.

File: pgdog/src/backend/replication/logical/orchestrator.rs [hunk 4]
```diff
@@ -74,6 +74,19 @@ impl Orchestrator {
         self.publisher = Arc::new(Mutex::new(publisher));
     }
 
+    /// Refresh cluster references and the publisher's source pool after a
+    /// long-running operation (e.g. data_sync).  Must NOT recreate the
+    /// publisher — that would discard the table LSN state accumulated during
+    /// the copy.  Instead, only the cluster reference inside the existing
+    /// publisher is updated so that subsequent pool.get() calls target the
+    /// live pool rather than a stale, potentially-offline one.
+    pub(crate) async fn refresh_before_replicate(&mut self) -> Result<(), Error> {
```
Comment (levkk) [inline pgdog/src/backend/replication/logical/orchestrator.rs:83]: I think we have code to do this already somewhere. If not, we should re-use this function wherever we run these 3 statements.

File: pgdog/src/backend/pool/pool_impl.rs (hunk 1 above)
Comment (meskill) [reply pgdog/src/backend/pool/pool_impl.rs:367]: the intention was to add more logs that will help with tracing the similar issues. 

I can drop it or change the severity/message

File: pgdog/src/backend/replication/logical/publisher/table.rs (hunk 3 above)
Comment (meskill) [reply pgdog/src/backend/replication/logical/publisher/table.rs:77]: it is, the added tests validate that. I'll investigate if we can identify this actually

File: pgdog/src/backend/pool/pool_impl.rs (hunk 1 above)
Comment (levkk) [reply pgdog/src/backend/pool/pool_impl.rs]: Yup makes sense. You can set this to `trace` level for sure.

Comment (meskill) [reply pgdog/src/backend/pool/pool_impl.rs]: changed the logs

File: pgdog/src/backend/replication/logical/publisher/publisher_impl.rs (hunk 2 above)
Comment (meskill) [reply pgdog/src/backend/replication/logical/publisher/publisher_impl.rs]: updated this to show more relevant error and to collect multiple errors

File: pgdog/src/backend/replication/logical/publisher/table.rs (hunk 3 above)
Comment (meskill) [reply pgdog/src/backend/replication/logical/publisher/table.rs:79]: so, this will require custom handling in validation and in query generation. Let me actually do this as a separate pr to make it more focused

File: pgdog/src/backend/replication/logical/orchestrator.rs (hunk 4 above)
Comment (meskill) [reply pgdog/src/backend/replication/logical/orchestrator.rs]: yes, there was the usual `refresh` but it was resetting the publication as well. I refactored this part and added tests, so now there is only one single `refresh` method

File: pgdog/src/backend/databases.rs [hunk 5]
```diff
@@ -126,19 +125,18 @@ pub fn reload() -> Result<(), Error> {
     let old_config = config();
     let new_config = load(&old_config.config_path, &old_config.users_path)?;
     let databases = from_config(&new_config);
-
+    info!(
+        "reloading pools from config file: {}",
```
Comment (levkk) [inline pgdog/src/backend/databases.rs]:
```suggestion
        "reloading configuration",
```

This will reload `users.toml` too. Also `load` above logs this info already.

File: pgdog/src/frontend/client/query_engine/hooks/schema.rs [hunk 6]
```diff
@@ -1,5 +1,8 @@
+use tracing::debug;
+
 use crate::backend::{databases::reload_from_existing, Error};
 
 pub(crate) fn schema_changed() -> Result<(), Error> {
+    debug!("schema change detected: reloading pools to refresh schema cache");
```
Comment (levkk) [inline pgdog/src/frontend/client/query_engine/hooks/schema.rs]:
```suggestion
    debug!("schema change detected, refreshing schema cache");
```

File: integration/copy_data/setup.sql [hunk 7]
```diff
@@ -24,7 +24,13 @@ CREATE TABLE IF NOT EXISTS copy_data.orders (
     refunded_at TIMESTAMPTZ
 );
 
+-- TODO: remove the surrogate `id` column once pgdog supports replicating tables
+-- that have no primary key and no `REPLICA IDENTITY USING INDEX`. Without a PK
+-- (or unique index promoted via REPLICA IDENTITY USING INDEX), no column carries
+-- the replica identity flag, Table::valid() fails with NoIdentityColumns, and the
+-- table is rejected before the copy starts. See docs/FIX_ISSUE_914.md, Fix 2.
```
Comment (levkk) [inline integration/copy_data/setup.sql:31]: I wonder how it worked before...maybe because we never used upserts? But we do actually check that each table has a replica identity, so I'm not sure.

**Review by levkk — APPROVED** [review]
LGTM, minor logging changes only

File: integration/copy_data/setup.sql (hunk 7 above)
Comment (meskill) [reply integration/copy_data/setup.sql:31]: I think it's because the previous test didn't generate any replication messages to new database to hit the path where we do the `table.valid`, just a COPY thing only for data.
